Rpclib3
mghro/cradle pull request #232
Opened 2023-03-07 14:26 UTC by urlofmar

My contributions from the last few months; main topics: rpclib server, remote caching
Identical to the rpclib2 branch content-wise, but squashed some commits.
Still a huge diff I'm afraid...

2023-03-20 13:49 UTC, tmadden requested changes

2023-03-21 07:47 UTC, urlofmar commented on src/cradle/inner/io/http_requests.cpp
> +    s << get_value_id(x);
Will change.
(I copied this code verbatim from former preprocessor output, which also gave all-lowercase output.)

2023-03-21 08:21 UTC, urlofmar commented on src/cradle/inner/utilities/for_async.h
> +        std::forward<Function>(function)(*i);
Will remove the std::forward (as discussed)

2023-03-21 08:32 UTC, urlofmar commented on src/cradle/inner/core/type_interfaces.cpp
> +    return blob{owner, owner->bytes(), owner->size()};
Same answer here :smile:

2023-03-21 08:32 UTC, urlofmar commented on src/cradle/inner/core/type_interfaces.cpp
> +    return blob{owner, owner->bytes(), size};
And here...

2023-03-21 08:37 UTC, urlofmar commented on src/cradle/typing/encodings/msgpack.cpp
> +    return blob{wrapper, data, size};
Yes, will change

2023-03-21 08:47 UTC, urlofmar commented on src/cradle/inner/blob_file/blob_file_dir.cpp
> +// Finds the lowest file_id for which no "blob_{file_id}" file yet exists.
Will rephrase comment

2023-03-21 09:18 UTC, urlofmar commented on tests/unit/thinknode/caching.cpp
> +TEST_CASE("lazily generated cached tasks", tag)
Yes, the previous test case used to rely on an interface that was designed away. The test case was adapted accordingly, and now the two indeed are the same. Will remove the first one.

2023-03-21 09:50 UTC, urlofmar commented on src/cradle/inner/encodings/cereal.h
> +template<typename Archive>
Maybe there is, but it won't be a good one. Will change.

2023-03-21 10:16 UTC, urlofmar commented on docs/cache.md
> +* A secondary cache: a local disk cache (default size: 4GB) or a [remote cache](remote_cache.md)
As discussed, the Bazel remote server already gives two more levels: a local disk cache, and a cloud-based cache.

2023-03-21 10:22 UTC, urlofmar commented on docs/remote_cache.md
> +
We can revisit this topic when we add changes to the CRADLE framework that would need this.

2023-03-21 10:32 UTC, urlofmar commented on docs/cache.md
> +It looks like the LRU mechanism is not active for this disk cache.
The statement seems incorrect. I'll remove it.

2023-03-21 18:30 UTC, urlofmar commented on cmake/deploy_dir.h.in
> +    return "@deploy_dir@/rpclib_server@exe_ext@";
The new rules are:
- In a production environment, the RPC server should be on the PATH
- Unit tests find it in the deploy directory
- Integration tests find it in the directory containing `websocket_server`

2023-03-22 08:57 UTC, urlofmar commented on src/cradle/inner/requests/generic.h
> +    domain_name() const = 0;
Maybe some kind of mixed domain, or the Thinknode aspect should be leading?! Follow-up on #233. The structure of contexts and domains seems far from final...

2023-03-22 09:02 UTC, urlofmar commented on src/cradle/thinknode/context.h
> +struct thinknode_request_context : public cached_introspective_context_intf,
Yes, I agree. With the upcoming async changes it will only become worse, but maybe that will also make it clearer how the situation could be improved, so I suggest not to try and solve it now.

2023-03-22 16:20 UTC, merged